#!/bin/zsh

positional=()
  while [[ $# -gt 0 ]]; do
    arg=$1
    if [[ ${1[1,1]} == '+' ]]; then
      arg=$(runs lookup commit ${1[2,-1]} --porcelain)
      if [[ $arg =~ 'No runs match pattern.*' ]]; then
        runs ls
        exit
      fi
    fi
    positional+=("$arg") # save it in an array for later
    shift # past argument ;;
  done
set -- "${positional[@]}" # restore positional parameters
/usr/bin/git "$@"
